---
title: "Forschungsvorhaben: Systematisches Review zum Einsatz Künstlicher Intelligenz in der transdiagnostischen Psychiatrie"
author: "Anne-Kathrin Kleine"
bibliography: "Transdiagnostic_review.bib"
keywords: "artificial intelligence, mental healthcare"
csl: "../../config/apa.csl"
execute:
  echo: false
  warning: false
  message: false
  cache: true
  include: true
prefer-html: true
format: 
  docx:
    reference-doc: "../../config/template_word.docx"
  html:
    toc: true
    toc-depth: 3
editor: 
  markdown: 
    wrap: 72
---


Künstliche Intelligenz (KI) kommt in der psychischen Gesundheitsversorgung aktuell noch in Einzelfällen zum Einsatz, gewinnt jedoch zunehmend an Bedeutung. So werden beispielsweise auf KI-Modellen verwendet, um basierend auf Daten aus biologischen Signalen (z.B. EEG) Symptomprofile zu erstellen, die eine personalisierte, störungsübergreifende (transdiagnostische) Behandlung ermöglichen [@rosenfeld_etal21a]. 
Das Ziel transdiagnostischer Psychiatrie ist es, sich von konventionellen diagnostischen Kategorien (z.B. DSM) zu lösen und Individuen anhand ihrer Verhaltensmuster und biologischen Zustände einzuschätzen. Transdiagnostische Forschung kann mit herkömmlichen inferenziellen Methoden schwer umgesetzt werden, da deren statistische Aussagekraft durch klar voneinander abgrenzbare Gruppen generiert wird. KI-basierte Vorhersagemodelle hingegen berücksichtigen die Heterogenität von Symptomen innerhalb und zwischen Patienten und 'gesunden' Individuen. So können KI-Modelle genutzt werden, um Individuen basierend auf biologischen Messwerten (z.B. EEG Daten) in kleinere Subgruppen einzuteilen. Die Behandlung datengestützter Subgruppen kann zu verbesserten Therapieerfolgen führen [@tejavibulya_etal22]. 

Für das Forschungsprojekt plane ich ein systematisches Review aktueller Fachliteratur (ab 2018) zum Einsatz von KI in der transdiagnostischen Psychiatrie. Die Arbeit basiert auf dem Artikel „Transdiagnostic psychiatry: A systematic review“ von @fusar-poli_etal19a. Im Rahmen des Reviews sollen transdiagnostische KI-gestützte Ansätze entsprechend der Definition von @mansell_etal09 identifiziert und anhand mehrerer Kriterien (z.B. transdiagnostisches Konzept und Fokus) kategorisiert werden. Sofern vorhanden, sollen Informationen zur Wirksamkeit des transdiagnostischen Ansatzes im Vergleich zu konventionellen diagnostischen Kriterien und Behandlungsmethoden dargestellt werden [@fusar-poli_etal19a]. 

KI-basierte Vorhersagemodelle spielen eine Schlüsselrolle in der Entwicklung neuer transdiagnostischer Ansätze in der Psychiatrie [@tejavibulya_etal22]. Mit dem detaillierten Überblick aktueller Forschung zu KI in der transdiagnostischen Psychiatrie soll das Review eine Grundlage für zukünftige Studien und Entwicklungen in diesem Bereich schaffen. 

# Referenzen

::: {#refs custom-style="Bibliography"}
:::
